#cloud-config

groups:
- sudo
- docker # even if package is not installed

users:
- name: lrivallain
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: users, admin, sudo, docker
  ssh-import-id: gh:lrivallain # Optional. Import SSH ids
  lock_passwd: true # Defaults to true. Lock the password to disable password login

package_update: true  # Update packages database on first boot
package_upgrade: true # Upgrade the packages on first boot
packages:
- zsh
- vim
- curl
- python3
- zsh
- ack
- jq
- httpie
- tmux

runcmd:
# authorize chsh with no password sudo users
- sed -i 's/required   pam_shells.so/sufficient   pam_shells.so/g' /etc/pam.d/chsh

final_message: "The system is finally configured, after $UPTIME seconds"
