name: Deploy a test VM to test the dotfiles installation

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 7 * * 0' # Runs at 07:00 UTC on Sun.


jobs:
  deploy:
    name: Quick deployment test
    runs-on: ubuntu-latest
    steps:
    - name: Initial checkout
      uses: actions/checkout@master
      with:
        path: working-repo
    - name: Configure the complete profile
      run: |
        bash working-repo/.dotfiles-scripts/install.sh
